  graph LR
    subgraph Browser
      LocalStorage((Local Storage))
    end
    subgraph Server
      subgraph "Token Generation"
        GenerateToken((Generate Token))
        Redis((Redis))
        LocalStorage --> GenerateToken --> Redis
      end
    subgraph "Token Verification"
        TokenVerification((Token Verification))
        Redis --> TokenVerification
        TokenVerification -->|Authenticated| VideoStream((Video Stream))
      end
    end
