---
title: Creating or Generating a Room
---
sequenceDiagram
    actor Alice
    participant OTT as OTT website
    participant L as Load Balancer
    participant N as Monolith
    alt Room Generation
    Alice->>+OTT: Hello, I want to generate a room
    OTT->>+L: Start connection
    Note over L: Determines which node has least load
    L->>+N: New room "uuid" generated
    N->>-L: Joined
    L->>-OTT: Joined
    OTT->>-Alice: Joined
    Note over Alice,N: Alice's connection to OTT is transparently proxied to Node
    else Room Creation
    Alice->>+OTT: Hello, I want to create room "foo"
    OTT->>+L: Send user inputs
    Note over L: Determines which node has least load
    L->>+N: "foo" is created
    N->>-L: Joined
    L->>-OTT: Joined
    OTT->>-Alice: Joined
    Note over Alice,N: Alice's connection to OTT is transparently proxied to Node
    end