C4Deployment
    %% title Current OpenTogetherTube Deployment

    System_Boundary(browser, "Web Browser") {
        Person(user, "User")
        Component(frontend, "Frontend", "Vue, Typescript")
    }


    System_Boundary(ott, "OpenTogetherTube") {
        Container(monolith, "Monolith", "Typescript, Javascipt")
        SystemDb(postgres, "Postgres", "Persists Users, Rooms")
        SystemDb(redis, "Redis", "Caching, Session Store")
    }

    Rel(user, frontend, "Uses")
    Rel(frontend, monolith, "Uses", "REST API, websockets")
    Rel(monolith, postgres, "Read/Write")
    Rel(monolith, redis, "Read/Write")

    UpdateLayoutConfig($c4ShapeInRow="2", $c4BoundaryInRow="1")
