  flowchart LR
    User((User)) -->OpenTogetherTube((OpenTogetherTube))
    OpenTogetherTube --> Search((Search))
    Search -->Video((Video))
    Video --> Watch((Watch))
    Watch -->Comment((Comment))
    Watch --> Share((Share))