---
title: Monolith's Current Internals
---
classDiagram
    class Monolith {
        <<service>>
    }

    Monolith --> RoomManager
    Monolith --> ClientManager

    class Redis {
        <<service>>
    }

    class RoomManager {
        Room[] room
    }

    RoomManager "1" --> "0..*" Room

    class Room {
        String name
        bool isTemporary
        Visibility visibility
        RoomUser[] users
        ...
    }

    Room "1" --> "1" Visibility

    class Visibility {
        <<enumeration>>
        Public
        Unlisted
        Private
    }

    class ClientManager {
        Client[] connections
        Map roomStates
        Map roomJoins
    }

    RoomManager .. ClientManager: via Redis Pubsub
    RoomManager --> Redis
    ClientManager --> Redis

    class Client {
        String id
        WebSocket socket
        SessionInfo session
        String room
        AuthToken token
    }

    ClientManager --> Client

    class RoomUser {
        String id
        AuthToken token
    }

    Room "1" --> "0..*" RoomUser
    RoomUser "1" <.. "1" Client: represented by
