flowchart LR
    Clients[Web clients] --> Balancer

    A[Monolith]
    B[Monolith]

    Balancer --> A
    Balancer --> B

    Redis[(Redis)]
    Postgres[(Postgres)]

    A --> Redis
    A --> Postgres
    B --> Redis
    B --> Postgres